# Generated by Django 2.1.2 on 2018-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_auto_20181121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='Designação'),
        ),
    ]
