# Generated by Django 2.1.2 on 2018-11-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20181121_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='energia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='QA.Energia'),
        ),
    ]
