# Generated by Django 2.1.2 on 2018-11-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_auto_20181122_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='energia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='QA.Energia'),
            preserve_default=False,
        ),
    ]
